### ISSUE TITLE
Uncontrollable camera rotation

### ISSUE THREAD

**Issue by ThirteenAG** [TheOfficialFloW/GTA_Remastered#2]
I checked both LCS and VCS, same thing happens: camera just rotates around the player and there's no way to control it.
I believe I have EUR versions, let me know if you need any additional info.
PS. Swapping X and R works.

**Comment by TheOfficialFloW** [comment]
Can you try disabling right analog in the official settings?

**Comment by ThirteenAG** [comment]
Yeah, I did that(in the menu that appears by holding PS button), but same thing happens.

**Comment by ThirteenAG** [comment]
Is Adrenaline required for this plugin? Because I'm trying on 3.36 with TN-V, maybe that's why it works that way.

**Comment by TheOfficialFloW** [comment]
Lol. Closed

**Comment by ThirteenAG** [comment]
Yeah, perhaps mention that in the readme, I usually don't keep my vita up to date, just wanted to see how this thing works real quick :)
