### ISSUE TITLE
gta vcs - helicopter UP is turning around - unplayable

### ISSUE THREAD

**Issue by ssssss789** [TheOfficialFloW/GTA_Remastered#4]
gta vcs - helicopter UP is turning around - unplayable

**Comment by adamhun94** [comment]
^ I can confirm this. You can accelerate the heli with R, and it also turns right.

**Comment by ssssss789** [comment]
i resolved it and completed game:

1. easy helicopter missions - hold R + L to go up and control it from front view camera
2. hard heli mission (only one with container on car) -  quit game, rename ms0:/seplugins to ms0:/sepluginsX which disable it, play mission, rename ms0:/sepluginsX to ms0:/seplugins and continue play

**Comment by adamhun94** [comment]
I'm through these missions, and I also used these methods. Actually you don't need to rename the folder. In the XMB (psp menu) if you press 'select', in the popup menu you can enter Recovery and there are options to enable/disable plugins.

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/GTA_Remastered/commit/098dccb8d2464c8a599800478eeae47046b4528d
