### ISSUE TITLE
Option to invert look?

### ISSUE THREAD

**Issue by tommikinder** [TheOfficialFloW/GTA_Remastered#6]
Would you be able to compile a version with the Y-axis inverted? The in game option to invert doesn't change it unfortunately.

**Comment by rereprep** [comment]
solution: http://wololo.net/talk/viewtopic.php?p=417399#p417399

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/GTA_Remastered/commit/098dccb8d2464c8a599800478eeae47046b4528d
