### ISSUE TITLE
Free Aim Improvement

### ISSUE THREAD

**Issue by LameNobody** [TheOfficialFloW/GTA_Remastered#8]
Free Aim - Hold R and press D-pad Down.

Issue: when using free aim, player cannot walk, both sticks move camera

Cause: Left analog is still used for free aim (the plugin is also allowing the right stick to be used at the same time to aim, however the left stick is also forced to move the camera)

Solution: When user enters free aim mode, allow walking with the left stick. (Another idea is to use the L shoulder button to free aim)

**Comment by TheOfficialFloW** [comment]
Not an issue.
